<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- VERY IMPORTANT -->
		<OutputType>Exe</OutputType>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TalentFlow.Application\TalentFlow.Application.csproj" />
		<ProjectReference Include="..\TalentFlow.Infrastructure\TalentFlow.Infrastructure.csproj" />
	</ItemGroup>

</Project>